# Generated by Django 4.2.19 on 2025-06-24 10:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('first_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('action_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookingCode',
            fields=[
                ('bc_id', models.AutoField(primary_key=True, serialize=False)),
                ('sportyBet_code', models.CharField(default='', max_length=250)),
                ('betWay_code', models.CharField(default='', max_length=250)),
            ],
            options={
                'db_table': 'BookingCode',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('league', models.TextField()),
                ('team1', models.TextField()),
                ('team2', models.TextField()),
                ('prediction', models.TextField()),
                ('prediction_type', models.TextField()),
                ('result', models.CharField(max_length=450)),
                ('odd', models.CharField(max_length=450)),
                ('matchday', models.DateField(default=datetime.datetime(2025, 6, 24, 10, 36, 40, 119855, tzinfo=datetime.timezone.utc))),
                ('time_created', models.TimeField(default=datetime.datetime(2025, 6, 24, 10, 36, 40, 119892, tzinfo=datetime.timezone.utc))),
                ('date_created', models.DateField(default=datetime.datetime(2025, 6, 24, 10, 36, 40, 119909, tzinfo=datetime.timezone.utc))),
                ('game_type', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'games',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('notification_date', models.DateField(auto_now=True)),
                ('seen', models.BooleanField(default=False)),
                ('cleared', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Notifications',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Slips',
            fields=[
                ('slip_id', models.AutoField(primary_key=True, serialize=False)),
                ('results', models.TextField()),
                ('total_odd', models.CharField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('match_day', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('free', 'Free'), ('vvip1', 'DAILY VVIP PLAN'), ('vvip2', 'DAILY VVIP PLAN 2'), ('vvip3', 'DAILY VVIP PLAN 3'), ('vip', 'VIP PLAN')], default='', max_length=50)),
                ('date_created', models.DateField()),
                ('booking_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wonitApi.bookingcode')),
                ('games', models.ManyToManyField(related_name='slips', to='wonitApi.games')),
            ],
            options={
                'db_table': 'Slips',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(default='233')),
                ('purchase_date', models.DateField(auto_now=True)),
                ('slip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wonitApi.slips')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wonitApi.authuser')),
            ],
            options={
                'db_table': 'Purchases',
                'managed': True,
            },
        ),
    ]
