# Generated by Django 4.2.19 on 2025-07-01 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wonitApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2025, 7, 1, 23, 40, 10, 524922, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='games',
            name='matchday',
            field=models.DateField(default=datetime.datetime(2025, 7, 1, 23, 40, 10, 524873, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='games',
            name='time_created',
            field=models.TimeField(default=datetime.datetime(2025, 7, 1, 23, 40, 10, 524907, tzinfo=datetime.timezone.utc)),
        ),
    ]
