# Generated by Django 4.2.19 on 2025-09-19 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wonitApi', '0002_alter_games_date_created_alter_games_matchday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slips',
            name='status',
            field=models.CharField(default='pending', max_length=250),
        ),
        migrations.AlterField(
            model_name='games',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2025, 9, 19, 11, 16, 34, 327498, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='games',
            name='matchday',
            field=models.DateField(default=datetime.datetime(2025, 9, 19, 11, 16, 34, 327461, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='games',
            name='time_created',
            field=models.TimeField(default=datetime.datetime(2025, 9, 19, 11, 16, 34, 327487, tzinfo=datetime.timezone.utc)),
        ),
    ]
