# Generated by Django 4.2.19 on 2025-09-22 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wonitApi', '0003_slips_status_alter_games_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2025, 9, 22, 23, 25, 43, 431978, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='games',
            name='matchday',
            field=models.DateField(default=datetime.datetime(2025, 9, 22, 23, 25, 43, 431940, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='games',
            name='time_created',
            field=models.TimeField(default=datetime.datetime(2025, 9, 22, 23, 25, 43, 431967, tzinfo=datetime.timezone.utc)),
        ),
    ]
