# Generated by Django 4.2.19 on 2025-05-09 22:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wonitApi', '0003_remove_games_prediction_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slips',
            name='price',
            field=models.CharField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slips',
            name='total_odd',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='games',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2025, 5, 9, 22, 0, 2, 154900, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='games',
            name='matchday',
            field=models.DateField(default=datetime.datetime(2025, 5, 9, 22, 0, 2, 154868, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='games',
            name='time_created',
            field=models.TimeField(default=datetime.datetime(2025, 5, 9, 22, 0, 2, 154891, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateField(auto_now=True)),
                ('slip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wonitApi.slips')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wonitApi.authuser')),
            ],
            options={
                'db_table': 'Purchases',
                'managed': True,
            },
        ),
    ]
