# Generated by Django 4.2.19 on 2025-05-09 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wonitApi', '0004_slips_price_slips_total_odd_alter_games_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2025, 5, 9, 22, 57, 24, 890553, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='games',
            name='matchday',
            field=models.DateField(default=datetime.datetime(2025, 5, 9, 22, 57, 24, 890525, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='games',
            name='time_created',
            field=models.TimeField(default=datetime.datetime(2025, 5, 9, 22, 57, 24, 890544, tzinfo=datetime.timezone.utc)),
        ),
    ]
