# Generated by Django 4.2.19 on 2025-05-09 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wonitApi', '0005_alter_games_date_created_alter_games_matchday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2025, 5, 9, 23, 6, 48, 636849, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='games',
            name='matchday',
            field=models.DateField(default=datetime.datetime(2025, 5, 9, 23, 6, 48, 636814, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='games',
            name='time_created',
            field=models.TimeField(default=datetime.datetime(2025, 5, 9, 23, 6, 48, 636832, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='slips',
            name='games',
            field=models.ManyToManyField(related_name='slips', to='wonitApi.games'),
        ),
    ]
