# Generated by Django 4.2.19 on 2025-05-09 23:10

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('wonitApi', '0006_alter_games_date_created_alter_games_matchday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='Slips',
            name='games',
            field=models.ManyToManyField(related_name='slips', to='wonitApi.games'),
        ),
    ]
