# Generated by Django 4.2.19 on 2025-05-13 21:48

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wonitApi', '0008_slips_booking_code_alter_games_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingcode',
            name='code',
        ),
        migrations.AddField(
            model_name='bookingcode',
            name='betWay_code',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='bookingcode',
            name='sportyBet_code',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='slips',
            name='match_day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='slips',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='games',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2025, 5, 13, 21, 48, 28, 380703, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='games',
            name='matchday',
            field=models.DateField(default=datetime.datetime(2025, 5, 13, 21, 48, 28, 380614, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='games',
            name='time_created',
            field=models.TimeField(default=datetime.datetime(2025, 5, 13, 21, 48, 28, 380678, tzinfo=datetime.timezone.utc)),
        ),
    ]
