# Generated by Django 4.2.19 on 2025-05-18 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wonitApi', '0010_slips_category_alter_games_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='reference',
            field=models.CharField(default='233'),
        ),
        migrations.AlterField(
            model_name='games',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2025, 5, 18, 16, 5, 26, 338193, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='games',
            name='matchday',
            field=models.DateField(default=datetime.datetime(2025, 5, 18, 16, 5, 26, 338131, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='games',
            name='time_created',
            field=models.TimeField(default=datetime.datetime(2025, 5, 18, 16, 5, 26, 338175, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='slips',
            name='category',
            field=models.CharField(choices=[('free', 'Free'), ('vvip1', 'DAILY VVIP PLAN'), ('vvip2', 'DAILY VVIP PLAN 2'), ('vvip3', 'DAILY VVIP PLAN 3'), ('vip', 'DAILY VIP PLAN')], default='', max_length=50),
        ),
    ]
