# Generated by Django 4.2.19 on 2025-05-24 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wonitApi', '0012_notifications_alter_games_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notifications',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='games',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2025, 5, 24, 23, 42, 21, 326736, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='games',
            name='matchday',
            field=models.DateField(default=datetime.datetime(2025, 5, 24, 23, 42, 21, 326702, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='games',
            name='time_created',
            field=models.TimeField(default=datetime.datetime(2025, 5, 24, 23, 42, 21, 326724, tzinfo=datetime.timezone.utc)),
        ),
    ]
